steps:
- id: 'tf init'
  name: 'hashicorp/terraform:latest'
  args:
    - init
    - -no-color

- id: 'tf validate'
  name: 'hashicorp/terraform:latest'
  args:
    - validate
    - -no-color

- id: 'tf fmt'
  name: 'hashicorp/terraform:latest'
  args:
    - fmt
    - -recursive
    - -check
    - -no-color

- id: 'tf plan'
  name: 'hashicorp/terraform:latest'
  args:
    - plan
    - -no-color
    - -lock=false

options:
  logging: CLOUD_LOGGING_ONLY
