steps:
- id: 'tf init'
  name: 'hashicorp/terraform:latest'
  script: |
    #!/bin/sh
    set -e
    
    for d in */; do
      cd $d
      echo "Running 'init' in ${d}"
      terraform init -no-color
      echo; echo
      cd -
    done
    

- id: 'tf validate'
  name: 'hashicorp/terraform:latest'
  script: |
      #!/bin/sh 
      set -e
      
      for d in */; do
        cd $d
        echo "Running 'validate' in ${d}"
        terraform validate -no-color
        echo; echo
        cd -
      done 

- id: 'tf fmt'
  name: 'hashicorp/terraform:latest'
  script: |
    #!/bin/sh
    set -e
    
    for d in */; do
      cd $d
      echo "Running 'fmt' in in ${d}"
      terraform fmt -recursive -check -no-color
      echo; echo
      cd -
    done

- id: 'tf apply'
  name: 'hashicorp/terraform:latest'
  script: |
    #!/bin/sh
    set -e
    
    for d in */; do
      cd $d
      echo "Running 'apply' in ${d}"
      terraform apply -auto-approve -no-color
      echo; echo
      cd -
    done

options:
  logging: CLOUD_LOGGING_ONLY