steps:
- id: 'tf init'
  name: 'hashicorp/terraform:latest'
  script: |
    #!/bin/sh
    
    for d in */; do
      cd $d
      echo "in ${d}"
      terraform init
      if [ $? -ne 0 ]; exit $?; fi
      cd -
    done
    

- id: 'tf validate'
  name: 'hashicorp/terraform:latest'
  script: |
      #!/bin/sh
      
      for d in */; do
        cd $d
        echo "in ${d}"
        terraform validate -no-color
        if [ $? -ne 0 ]; exit $?; fi
        cd -
      done

- id: 'tf fmt'
  name: 'hashicorp/terraform:latest'
  script: |
    #!/bin/sh
    
    for d in */; do
      cd $d
      echo "in ${d}"
      terraform fmt -recursive -check -no-color
      if [ $? -ne 0 ]; exit $?; fi
      cd -
    done

- id: 'tf apply'
  name: 'hashicorp/terraform:latest'
  script: |
    #!/bin/sh
    
    for d in */; do
      cd $d
      echo "in ${d}"
      terraform apply -auto-approve -no-color
      if [ $? -ne 0 ]; exit $?; fi
      cd -
    done

options:
  logging: CLOUD_LOGGING_ONLY
