steps:
- id: 'tf init'
  name: 'hashicorp/terraform:latest'
  env:
  - TF_VAR_org_id=${_ORG_ID}
  - TF_VAR_billing_account_id=${_BILLING_ACCOUNT_ID}
  - TF_VAR_parent_folder=${_PARENT_FOLDER}
  - TF_VAR_state_bucket=${_TFSTATE_BUCKET}
  script: |
    #!/bin/sh
    set -e
    echo "ORG: ${TF_VAR_org_id}"
    for d in */; do
      cd $d
      echo; echo "Running 'init' in ${d}"; echo
      terraform init -no-color
      echo; echo
      cd -
    done
# - id: 'tf validate'
#   name: 'hashicorp/terraform:latest'
#   script: |
#       #!/bin/sh 
#       set -e

#       for d in */; do
#         cd $d
#         echo; echo "Running 'validate' in ${d}"; echo
#         terraform validate -no-color
#         echo; echo
#         cd -
#       done 

# - id: 'tf fmt'
#   name: 'hashicorp/terraform:latest'
#   script: |
#     #!/bin/sh
#     set -e

#     for d in */; do
#       cd $d
#       echo; echo "Running 'fmt' in in ${d}"; echo
#       export TF_VAR_org_id=${_ORG_ID}
#       export TF_VAR_billing_account_id=${_BILLING_ACCOUNT_ID}
#       terraform fmt -recursive -check -no-color
#       echo; echo
#       cd -
#     done

- id: 'tf apply'
  name: 'hashicorp/terraform:latest'
  env:
  - TF_VAR_org_id=${_ORG_ID}
  - TF_VAR_billing_account_id=${_BILLING_ACCOUNT_ID}
  - TF_VAR_parent_folder=${_PARENT_FOLDER}
  - TF_VAR_state_bucket=${_TFSTATE_BUCKET}
  script: |
    #!/bin/sh
    set -e

    for d in */; do
      cd $d
      echo; echo "Running 'apply' in ${d}"; echo
      terraform apply -auto-approve -no-color
      echo; echo
      cd -
    done

options:
  logging: CLOUD_LOGGING_ONLY