steps:
- id: 'tf init'
  name: 'hashicorp/terraform:latest'
  script: |
    #!/bin/sh
    
    for d in */; do
      cd $d
      echo "in ${d}"
      terraform init -no-color
      if [ $? -ne 0 ]; then exit $?; fi
      cd -
    done || exit 1
    

- id: 'tf validate'
  name: 'hashicorp/terraform:latest'
  script: |
      #!/bin/sh
      
      for d in */; do
        cd $d
        echo "in ${d}"
        terraform validate -no-color
        if [ $? -ne 0 ]; then exit $?; fi
        cd -
      done || exit 1

- id: 'tf fmt'
  name: 'hashicorp/terraform:latest'
  script: |
    #!/bin/sh
    
    for d in */; do
      cd $d
      echo "in ${d}"
      terraform fmt -recursive -check -no-color
      if [ $? -ne 0 ]; then exit $?; fi
      cd -
    done || exit 1

- id: 'tf apply'
  name: 'hashicorp/terraform:latest'
  script: |
    #!/bin/sh
    
    for d in */; do
      cd $d
      echo "in ${d}"
      terraform apply -auto-approve -no-color
      if [ $? -ne 0 ]; then exit $?; fi
      cd -
    done || exit 1

options:
  logging: CLOUD_LOGGING_ONLY